services:
  registry:
    image: registry:2.8.3
    container_name: registry
    hostname: registry
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./registry:/var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR-0.0.0.0:5005

  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./job.ini:/var/jenkins_home/job.ini 
      - ./jobs:/var/jenkins_jobs  
      # - ./runner_job.groovy:/var/jenkins_home/runner_job.groovy  
      # - ./update_job.groovy:/var/jenkins_home/update_job.groovy  
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"
      - DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - registry

  nginx:
    image: nginx:stable-perl
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - jenkins
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime